backend:
  name: github
  repo: matthewcrist/agile6
  branch: dev

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "people"
    label: "Team Member"
    folder: "src/content/team"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template", name: "templateKey", widget: "hidden", default: "team-member"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Picture", name: "picture", widget: image}

  - name: "capabilities"
    label: "Capability"
    folder: "src/content/capabilities"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "capability"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Short Description", name: "shortdescription", widget: "string"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Show on home page?", name: "featured", widget: "boolean", default: false, required: false}

  - name: "casestudies"
    label: "Case Study"
    folder: "src/content/case-studies"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "casestudy"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Short Description", name: "shortdescription", widget: "string"}
      - {label: "Logo", name: "logo", widget: image}
      - {label: "Background", name: "background", widget: image}
      - {label: "Show on home page?", name: "featured", widget: "boolean", default: false, required: false}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}